<?php 
define("TrangChu","TRANG CHỦ");
define("GioiThieu","GIỚI THIỆU");
define("KhuNghiDuong","KHU NGHỈ DƯỠNG");
define("KhuNghiDuong2","Khu nghỉ dưỡng");
define("ThamGia","THAM GIA");
define("TroGiup","TRỢ GIÚP");
define("LienHe","LIÊN HỆ");
define("DangNhapDangKy","Đăng nhập -  Đăng ký ngay");
define("TimHieuThem","Xem thêm");
define("NgonNgu","Chọn ngôn ngữ");
define("Ten","TÊN CỦA BẠN");
define("DienThoai","SỐ ĐIỆN THOẠI CỦA BẠN");
define("Email","EMAIL CỦA BẠN");
define("Gui","Gửi");
define("CauHoiThuongGap","Câu hỏi thường gặp");
define("CachSuDung","Cách sử dụng");

define("WhatIsTimeShare","TimeShare LÀ GÌ?");
define("TitleWhatIsTimeShare1","Timeshare là gì?");
define("ContentWhatIsTimeShare1","Timeshare có nhiều dạng khác nhau, tuy nhiên với nhiều hình thức và quy mô thì Timeshare được hiểu một cách phổ biến nhất như là kỳ nghỉ chia sẻ phòng ốc bởi các chủ nhà với nhau.");
define("TitleWhatIsTimeShare2","Khởi phát khi nào và ở đâu?");
define("ContentWhatIsTimeShare2","Ý tưởng timeshare được khởi phát vào đầu thế kỷ thứ 20 tại Châu Âu khi các gia đình có xu hướng muốn mua kỳ nghỉ tại gia với nhau. Những gia đình này đều cùng nhu cầu trao đổi quyền sở hữu của mình trong khoảng thời gian nghỉ như nhau gồm cả chi phí tu bổ cũng như sửa sang nhà cửa. Ví dụ như có khoảng 4 gia đình với thời gian sử dụng nhà 3 tháng/lần trong một năm.");
define("TitleActivitiesOfTimeShare","HOẠT ĐỘNG CỦA PPC TIMESHARE");
define("ContentActivitiesOfTimeShare","Các nhà đầu tư và phát triển dịch vụ Timeshare sẽ bán quyền lợi chia sẻ tài sản của mình trong kỳ nghỉ đó, điển hình có thể trong khoảng thời gian một tuần hoặc trọn gói tại các địa điểm mà bạn có thể tận hưởng những tiện nghi tốt nhất. Bên cạnh đó, các thành viên sẽ có cơ hội phát triển hoạt động Timeshare của chính mình trong tương lai và chỉ trả thêm phí duy trì sau lần đầu mua mà thôi.");
define("InternationalCorporation","HỢP TÁC QUỐC TẾ");
define("InternationalCorporation1","Tuần lễ PPC TIMESHARE");
define("TTInternationalCorporation1","MẠNG LƯỚI KHU NGHĨ DƯỠNG PHONG PHÚ");
define("CTInternationalCorporation11","Các bạn có thể tự do khám phá hơn 4.500 khu nghỉ dưỡng dưới sự lựa chọn cẩn thận với tuần Thành viên mà PPC phụ trách trong khoảng 100 quốc gia.");
define("TTInternationalCorporation12","Quy trình trao đổi rất đơn giản nếu bạn biết tới cách thức hoạt động. Chỉ cần đặt cọc gửi tiền tuần của bạn sớm nhất có thể với PPC Timeshare và chọn những tuần có sẵn mà các thành viên khác đã gửi vào trước đó rồi thực hiện trao đổi của bạn.");
define("ExchangeEasier","TRAO ĐỔI DỄ DÀNG HƠN");
define("TTInternationalCorporation2","ĐẶT CỌC CHO PPC");
define("CTInternationalCorporation2","Chỉ cần đặt cọc tại PPC Timeshare, cơ hội trao đổi các kỳ nghỉ của bạn sẽ được thúc đẩy và quan trọng là gửi tiền là hoàn toàn miễn phí. Bạn không cần phải quan tâm thời gian cũng như địa điểm mà bạn có ý định đi du lịch khi bạn đặt cọc. Bạn có thể lên kế hoạch Trao Đổi Kỳ Nghỉ của bạn vào một ngày nào đó sớm nhất. Bạn cũng có thể đặt cọc chi phí tuần lễ trên website hoặc gọi cho chúng tôi. ");
define("TTInternationalCorporation3","GIÚP BẠN TRAO ĐỔI KỲ NGHỈ");
define("CTInternationalCorporation3","Có thể bình thường đơn giản chỉ cần lên mạng để gửi những yêu cầu trao đổi kỳ nghỉ. Tuy nhiên nếu vào những ngày nghỉ bạn muốn trao đổi lại không có, đừng ngần ngại tìm chúng tôi và chúng tôi sẽ tiếp tục tìm kiếm cho bạn 24/7. Hoặc gọi cho chúng tôi và chúng ta sẽ cũng nhau trao đổi về các lựa chọn kỳ nghỉ của bạn. Điều quan trọng là đặt cọc tiền PPC Tuần Lễ của bạn càng sớm càng tốt, 2 năm trước ngày bắt đầu, để tối đa hóa khả năng giao dịch của bạn.");
define("TTInternationalCorporation4","XÁC NHẬN TRAO ĐỔI KỲ NGHỈ");
define("CTInternationalCorporation4","Khi bạn đã hoàn thành yêu cầu kỳ nghỉ của bạn, bạn sẽ nhận được xác nhận qua email hoặc bưu điện. Đừng quên mang theo mã xác nhận này theo tại bất kỳ đâu trong suốt kỳ nghỉ của bạn.");
define("InternationalCorporation2","MUA KỲ NGHỈ HÈ VỚI THẺ BẠCH KIM");
define("ContentInternationalCorporation2","Bạn đã làm việc chăm chỉ cho kỳ nghỉ này. Nhưng bạn đâu muốn kỳ nghỉ đó cũng khiến bạn mệt mỏi như vậy? Nâng cấp lên Platinum từ thành viên cho chỉ $50 và sẽ giúp bạn có được nhiều hơn một tuần như thế.");

define("DangNhap","ĐĂNG NHẬP");
define("TenDangNhap","Tên đăng nhập");
define("Password","Mật khẩu");
define("RememberPassword","Nhớ mật khẩu?");
define("DontHaveAccount","Bạn chưa có tài khoản?");
define("ForgotPassword","Quên mật khẩu?");
define("NutDangNhap","Đăng nhập");
define("Thoat","Thoát");
define("XinChao","Xin chào, ");
define("DoiMatKhau","Đổi mật khẩu");

define("TTDoiMatKhau","ĐỔI MẬT KHẨU");
define("MatKhauCu","Mật khẩu cũ");
define("MatKhauMoi","Mật khẩu mới");
define("NhapLaiMatKhau","Nhập lại mật khẩu");
define("NutDoiMatKhau","Lưu");
define("Nam","Nam");
define("Nu","Nữ");
define("TTDangKy","ĐĂNG KÝ");
define("DiaChiEmail","Địa chỉ thư điện tử");
define("DienThoaiDK","Số điện thoại");
define("HoTenDK","Họ tên");
define("DiaChiDK","Địa chỉ");
define("GioiTinhDK","Giới tính");
define("DangKy","Đăng ký");
define("VideoCuaChungToi","VIDEO CỦA CHÚNG TÔI");
define("ForgotPasswordUpper","QUÊN MẬT KHẨU?");
define("KhuNghiDuongGiaCa","KHU NGHỈ DƯỠNG & GIÁ CẢ");
define("DanhMucKhuNghiDuong","DANH MỤC KHU NGHỈ DƯỠNG");
define("GoiYChoKyNghi","GỢI Ý CHO KỲ NGHỈ");
define("KhamPhaCacDiaDiem","KHÁM PHÁ CÁC ĐỊA ĐIỂM");
define("CoGiMoiTaiTimeShare","CÓ GÌ MỚI TẠI PPC TIMESHARE");
define("UuDaiDacBiet","ƯU ĐÃI ĐẶC BIỆT");
define("KetNoiVoi","KẾT NỐI VỚI");
define("ThongCaoBaoChi","THÔNG CÁO BÁO CHÍ");
define("ViTri","VỊ TRÍ");
define("DichVuLuuTru","DỊCH VỤ LƯU TRÚ");
define("ThietBiVaDichVuLuuTru","THIẾT BỊ VÀ DỊCH VỤ LƯU TRÚ");
define("DatCho","ĐẶT CHỖ");
define("NoiDung"," NỘI DUNG");
define("KhuVuc","Khu vực");
define("KhuNghiDuongVaGiaCa","KHU NGHỈ DƯỠNG & GIÁ CẢ");
define("DanhMucKhuNghiDuong1","Danh mục khu nghỉ dưỡng");
define("CoGiMoiTai","CÓ GÌ MỚI TẠI");
define("Loai","Loại");
define("TatCa","Tất cả");
define("HomeShare","Nhà");
define("SapXepTheo","Sắp xếp theo");
define("KhuyenMai","Khuyến mãi");
define("Moi","Mới");
define("XemThongTinCaNhan","Xem thông tin cá nhân");
define("Gia","Giá");
define("HinhDaiDien","Hình đại diện");
define("GioiTinh","Giới tính");
define("LichSuGiaoDich","Lịch sử giao dịch");
define("NgayNhanPhong","Ngày nhận phòng");
define("NgayTraPhong","Ngày trả phòng");
define("SoLuongPhong","Số lượng phòng");
define("NguoiLon","Người lớn");
define("TreNho","Trẻ nhỏ");
define("TheUuDai","Thẻ ưu đãi");
define("GhiChu","Ghi chú");
define("ThanhCong","Thành công");
define("HuyBo","Hủy bỏ");
define("ChuaDuyet","Chưa duyệt");
define("TrangThai","Trạng thái");
define("ThongTinCaNhan","Thông tin cá nhân");
define("ThongTinDatCho","THÔNG TIN ĐẶT CHỖ");