<?php 
define("TrangChu","HOME");
define("GioiThieu","INTRODUCTION");
define("KhuNghiDuong","RESORTS");
define("KhuNghiDuong2","Resort");
define("ThamGia","JOIN");
define("TroGiup","HELP");
define("LienHe","CONTACT");
define("DangNhapDangKy","LOGIN - REGISTER NOW");
define("TimHieuThem","Read More");
define("NgonNgu","Select language");
define("Ten","YOUR NAME");
define("DienThoai","YOUR PHONE NUMBER");
define("Email","YOUR EMAIL");
define("Gui","Send");
define("CauHoiThuongGap","Frequently Asked Questions");
define("CachSuDung","How to use");
define("HoTenDK","Full name");
define("DiaChiDK","Your address");
define("GioiTinhDK","Gender");
define("WhatIsTimeShare","What is Timeshare?");
define("TitleWhatIsTimeShare1","What is Timeshare?");
define("ContentWhatIsTimeShare1","Timeshare has many different forms, but with many forms and scales,  the timeshare is considered as sharing vacation about rooms and other facilities between accomodation owners.");
define("TitleWhatIsTimeShare2","when and where to departure ?");
define("ContentWhatIsTimeShare2","The idea of timeshare was come up in the early of 20th century in Europe when families tent to buy vacations at home together. These families had the same need in exchanging their ownership within the same period of vacation including accommodation decoration. For instance, about 4 families having time of use is once per 3 months in one year.");
define("TitleActivitiesOfTimeShare"," Timeshare Business");
define("ContentActivitiesOfTimeShare","Investors and Timeshare development services will sale rights of sharing properties in that vacation about one week or a whole package holiday in places that you can enjoy the best facilities. In addition, members will have opportunities to develop their own Timeshare business in the future and only pay extra fee after the first purchase.");
define("InternationalCorporation","INTERNATIONAL COOPERATION");
define("InternationalCorporation1","PPC Timeshare Week");
define("TTInternationalCorporation1","DIVERSITY OF RESORT NETWORK");
define("CTInternationalCorporation11","You can freely explore over 4,500 resorts under the careful selection for the member week that PPC is in charge of about 100 countries.");
define("TTInternationalCorporation12","Exchange process is easy if you know about the way of business. You only need to deposit weekly money for PPC Timeshare as soon as possible and choose available weeks that other members sent to the system before and carry out your transaction.");
define("ExchangeEasier","Exchange Easily");
define("TTInternationalCorporation2","DEPOSITING FOR PPC");
define("CTInternationalCorporation2","You only need to deposit in PPC Timeshare, your opportunity to exchange holiday will be promoted, moreover, money exchange is free. You do not need to concern time as well as locations that you want to travel when depositing. You can plan your holiday exchange on someday. You can deposit fee for that week on the website or giving us a phone call.");
define("TTInternationalCorporation3","HELPING YOUR VACATION EXCHANGE");
define("CTInternationalCorporation3","You frequently surf the internet to send your request about holiday exchange. However, if your request is not available, please find us and we will continue to seek for you all the time. You can give us a phone call and we will exchange about options of your holidays. More importantly, depositing money for your  PPC week as possible as and it should be deposit before 2 years to maximize your exchange ability.");
define("TTInternationalCorporation4","VACATION EXCHANGE CONFIRMATION");
define("CTInternationalCorporation4","When you complete your holiday request, you will receive the confirmation through an email or post office. Don’t forget to bring that confirmation code in anywhere during your holidays.");
define("InternationalCorporation2","PURCHASE SUMMER VACATION WITH PLANTINUM CARD");
define("ContentInternationalCorporation2","You work hard for this vacation. But you do not want that vacation to make you tired. Please upgrade your membership to Platinum with $50 and we will help your holidays better.");

define("DangNhap","LOGIN");
define("TenDangNhap","Username");
define("Password","Password");
define("RememberPassword","Remember password?");
define("DontHaveAccount","Don't have account?");
define("ForgotPassword","Forget password?");
define("ForgotPasswordUpper","FORGET PASSWORD?");
define("NutDangNhap","Login");
define("Thoat","Exit");
define("XinChao","Hello, ");
define("DoiMatKhau","Change Password");
define("Nam","Male");
define("Nu","Female");
define("TTDoiMatKhau","CHANGE PASSWORD");
define("MatKhauCu","Current password");
define("MatKhauMoi","New password");
define("NhapLaiMatKhau","Re-type new password");
define("NutDoiMatKhau","Save");

define("TTDangKy","REGISTER");
define("DiaChiEmail","Email");
define("DienThoaiDK","Number phone");
define("DangKy","Submit");

define("VideoCuaChungToi","OUR VIDEOS");


define("KhuNghiDuongGiaCa","RESORTS & PRICE");
define("DanhMucKhuNghiDuong","RESORT DIRECTORY");
define("GoiYChoKyNghi","HINTS FOR VACATION");
define("KhamPhaCacDiaDiem","DISCOVER PLACES");
define("CoGiMoiTaiTimeShare","WHAT'S UP IN PPC TIMESHARE ?");
define("UuDaiDacBiet","SPECIAL OFFERS");
define("KetNoiVoi","CONNECT WITH");
define("ThongCaoBaoChi","PRESS RELEASE FOR PPC TIMESHARE");
define("ViTri","LOCATION");
define("DichVuLuuTru","SERVICE");
define("ThietBiVaDichVuLuuTru","EQUIPMENT AND SERVICE");
define("DatCho","BOOK NOW");
define("NoiDung","CONTENTS");
define("KhuNghiDuongVaGiaCa","RESORT & COST PRICE");
define("DanhMucKhuNghiDuong1","RESORT DIRECTORY");
define("KhuVuc","Region");
define("CoGiMoiTai","WHAT 'S UP");
define("Loai","Type");
define("TatCa","All");
define("HomeShare","Home share");
define("SapXepTheo","Sort by");
define("KhuyenMai","Promotion");
define("Moi","New");
define("XemThongTinCaNhan","See personal Information");
define("Gia","Price");
define("HinhDaiDien","Avatar");
define("GioiTinh","Gender");
define("LichSuGiaoDich","Transaction History");
define("NgayNhanPhong","Check in");
define("NgayTraPhong","Check out");
define("SoLuongPhong","Quantity Of Room");
define("NguoiLon","Adult");
define("TreNho","Children");
define("TheUuDai","Voucher");
define("GhiChu","Note");
define("ThanhCong","Complete");
define("HuyBo","Cancel");
define("ChuaDuyet","Unapproved");
define("TrangThai","Status");
define("ThongTinCaNhan","Profile");

define("ThongTinDatCho","BOOK INFORMATION");
